#+TITLE: Financial Crisis
#+AUTHOR: Bush
#+EMAIL: junahan@outlook.com
#+DATE: 2019-01-07

Good morning. Our Nation is dealing with a serious financial crisis. Over the past month, Americans have witnessed fast-moving events involving complicated financial issue. I know many of you are concerned about your finances. So this morning, I want to tell you how we're addressing the uncertainty in our economy.

The federal government has responsed to this crisis with systematic and aggressive measures to protect the financial security of the American people. These actions will take more time to have their full impact. But they are big enough and bold enough to work. The primary focus of our efforts is addressing the underlying problem behind the freeze in our credit markets.

Earlier this month, Congress passed bipartisan legislation authorizing the Treasury Department to use up to $700 billion to help banks rebuild capital. This week, I announced that the Treasury will use a portion of that money to inject capital directly into banks by purchasing equity shares. This new capital will help banks continue making loans to businesses and consumers. In addition, the Treasure will use part of the $700 billion to purchase some of the troubled assets that are weighing down banks' balance sheets and clogging the financial system. This extraordinary effort is designed with one overriding purpose: to help banks get loans flowing to American consumers and businesses, so they can create jobs and grow our economy.

I know many Americans have reservations about the government's approach, especially about allowing the government to hold shares in private banks. As a strong believer in free markets, I would oppose such measures under ordinary circumstances. But these are no ordinary circumstances. Had the government not acted, the hole in our financial system would have grown larger, families and businesses would have had an even tougher time getting loans, and ultimately the government would have been forced to respond with even more drastic and costly measures later on. So I decided that government had to move, but that government's involvement in individual banks had to have prudent limits. 

The government's involvement is limited in size. The government will only buy a small percentage of shares in banks that choose to participate, so that private investors retain majority ownership. 

The government's involvement is limited in scope. The government will not exercises control over any private firm, and federal officials will not have a seat around your local bank's boardroom table. The shares owned by the government will have voting rights that can be used only to protect the taxpayer's investment - not to direct the firm's operations.

The government's involvement is limited in duration. It includes provisions to encourage banks to buy their shares back from the government when the markets stabilize and they can raise money from private investors. This will ensure that banks have an incentive to find private capital to replace the taxpayer's investment - and to do so quickly.

I know many of you are also concerned about the price tag of this rescue package. Ultimately, we believe the final cost will be significantly less than the initial investment. Many of the troubled assets that the government buys will increase in value as the market recovers. That means the government eventually will be able to resell them for a higher price. 

In addition, the government will receive quarterly dividends from the equity shares it purchases in financial institutions. If banks do not repurchase these shares within five years, the dividends they owe the government will increase substantially. This provides a clear incentive for banks to buy back their shares, thus returning the money to taxpayers, as soon as possible.

In a long run, the American people can have confidence that our economy will bounce back. 

American is the best place in the world to start and run a business, the most attractive destination for investors around the global, and home to the most talented, enterprising, and creative worker in the world. We're a country where all people have the freedom to realize their potential and chase their dreams.

This promise has defined our Nation since its founding, this promise will guide us through the challenges we face today, and this promise will continue to define our Nation for generations to come.

Thank you for listening.


