#+TITLE: Nuclear Security
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2019-01-06

Hi, everybody. This week, I'm speaking to you from our Nuclear Security Summit. I welcome more than 50 leaders from around the world to make sure we're working together to meet one of the greatest threats to global security - terrorists getting their hands on a weapon of mass destruction, like a nuclear weapon.

Fortunately, because of our efforts so far, no terrorist group has yet succeeded in obtaining a nuclear device or producing a dirty bomb using radioactive materials. But we know that al Qaeda has tried. ISIL has already used chemical weapons in Syria and Iraq. And if they ever got hold of a nuclear weapon or nuclear material, we have no doubt they'd use it. That's why we've been leading a global effort to secure the world's nuclear materials. And with summits like this, we've made important progress.

Working with other nations, we have removed or secured enough nuclear material for more than 150 nuclear weapons - material that will never fall into the hands of terrorists. All of South America is now free of these deadly materials. Central Europe and Southeast Asia are on track to be free of them later this year. That means that as terrorists and criminal gangs look around for the deadly ingredients for a nuclear device, vast regions of the world are now off limits. This is a remarkable achievement.

And at this summit, we pledged to keep up our efforts to prevent the world's most deadly networks from obtaining the world's most deadly weapons. Our summit was also another opportunity to make sure the world remains united and focused on destroying ISIL. A majority of the nations who came here are part of our global coalition against ISIL. 

A number of our countries have been targeted by ISIL. Just about all our nations have seen citizens travel to join ISIL in Syria and Iraq. In Syria and Iraq, ISIL continues to lose ground. Our coalition continues to take out its leaders, including those planning terrorist attacks against our conuntries. They're losing their oil infrastructure and revenuse. Their morale is suffering. 

As ISIL is squeezed in Syria and Iraq, it's lashing out elsewhere, as we've seen most recently - and tragically - from Turkey to Brussels. During our summit, we focused on ways to step up our efforts to disrupt terrorist attacks. It requires even more cooperation to prevent the flow of foreign terrorist fighters and sharing even more information and intelligence. That's why I invited all the nations represented at this summit to join us in a broader discussion among our intelligence and security services on how we can improve information sharing to prevent terrorist attacks.

This continues to be a difficult fight. But every day, our dedicated professionals - military, diplomatic, intelligence, counterterrorism, homeland security, law enforcement, nuclear exports - are working to protect us. Because of the progress we made this week, and over recent years, more of the world's nuclear material is secure. It's harder for terrorists to get it.

And as Commander in Chief, I want you to know that we're going to keep doing everything in our power to keep our nation safe and strong and free.

