#+TITLE: Happy Fourth of July
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-12-20

Hi everybody, and Happy Fourth of July weekend.

On Monday, Michelle, Malia, Sasha and I will celebrate the Fourth like most of you - in the backyard.

We'll hang out with family and friends, throw some burgers and dogs on the grill, and watch the fireworks show.

Of course, we're fortunate enough to have the South Lawn as our backyard.

So we're also going to fill it with hundreds of our troops, our veterans, and their families. Over the past seven and a half years, it's become one of my favorite traditions.

We get to celebrate our freedoms while doing what we can to honor all those who serve and sacrifice to make that freedom possible.

And I know that hornoring our service members, our veterans, and their families is something that so many Americans try to do every day, without fanfare, or expectation of anything in return.

For the past five years, Michelle and Dr. Jill Biden have tried to follow the example of so many of those Americans with their Joining Forces initiative.

They've rallied businesses to hire more than 1.2 million veterans and military spouses, and helped to reduce veteran homelessness.

And just this week, Michelle and Jill announced a breakthrough on a concern they've heard again and again from the military spouses they spend so much time with - and that's the issue of professional licensing.

This is something that most Americans aren't familiar with. But for military families, it's a big challenge. Here's why. Our troops are often transferred from base to base. It's part of the job. And because their families serve with them, that means their spouses move ten times more than the rest of us. Ten times more often. And I expect that's tough on a career.

And more than one in three of these sponses works in a profession that requires a professional license or certification. Nurses. Childcare providers. Accountants. Social workers. And lots of other jobs.

And until recently, when these sponses were asked to move across state lines, they often needed to re-certify for a job they've already qualified for. A nurse with years of experience might have to take entry-level courses, or pay a fee, or wait months for paperwork to be processed before he or she could get back to work on the job they love and that lets them support their families.

When Michelle and Jill took up this cause five years ago, only three states had taken action on military sponse licensing. But they rallied governers and state legislatures into action. And this week, we reached a milestone.

Today, all fifty state have acted to streamline many of these licensing issues. This is a big step forward, but we're not done yet. We're going to keep working with states to make licensing simpler for more jobs and reach more qualified workers. 

But we can finally say to so many of our military families - when you move, you'll no longer be forced to put the career you love on hold just because you and your familes have chosen to serve this country. That's what this is about - serving our man and women in uniform as well as they have served us.

But you don't have to be a governor or a Fist Lady to make a difference. So this holiday weekend, take a look at JoiningForces.gov to find out how you can serve the troops, veterans, and military families in your community.

And to all our brave men and women in uniform - you represent the best of who we are as a nation. On this day and every day, we thank you.

Have a great Fourth of July, everybody.





