#+TITLE: Bring Our Troops Home
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-12-2

This week, we had two powerful reminders of how w've renewed American leadership in the world.

I was proud to announce that - as promised - the rest of our troops in Iraq will com home by the end of this year.

And in Libya, the death of Moammar Qadhafi showed that our role in protecting the Libyan people, and helping them break free from a tyrant, was the right thing to do.

In Iraq, we've succeeded in our strategy to end the war.

Last year, I announced the end of our combat mission in Iraq.

We've already removed more than 100,000 troops, and Iraqi forces have taken full responsibility for the security of their own country.

Thanks to the extraoridinary sacrifices of our men and women in uniform, the Iraqi people have the chance to forge their own future.

And now the rest of our troops will be home for the holidays.

In Libya, our brave pilots and crews helped prevent a massacre, save countless lives, and give the Libyan people the chance to prevail.

Without putting a single U. S. service member on the ground, we achieved our objectives.

Soon, our NATO mission will come to a successful end even as we continue to support the Libyan people, and people across the Arab world, who seek a democratic future.

These successes are part of a large story.

After a decade of war, we're turning the page and moving forward, with strength and with confidence.

The drawdown in Iraq allowed us to refocus on Afghanistan and achieved major victories against al-Qaeda and Osama bin Laden.

As we remove the last of our troos from Iraq, we're beginning to bring our troops home from Afghanistan.

To put this in perspective, when I took office, roughly 180,000 troops were deployed in these wars.

By the end of this year that number will be cut in half, and an increasing number of our troops will continue to come home.

As we end these wars, we're focusing on our greatest challenge as a nation - rebuilding our economy and renewing our strength at home.

Over the past decade, we spend a trillion dollars on war, borrowed heavily from overseas and invested too little in the greastst source of our national strength - our own people.

Now, the nation we need to build is our own.

We have to tackle this challenge with the same urgency and the same unity that our troops brought to their fight.

That's why we have to do everything in our power to get our economy moving again.

That's why I'm calling on Congress to pass the American Job Act, so we can rebuild our country - our schools, our rouds, our bridges - and put our veterans, construction workers, teachers, cops and firefighters back to work.

And that's why I home all of us can draw strength from the esample of our men and women in uniform.

They've met their responsibilities to American.

Now that's time to meet ours.

It's time to come together and show the world why the United States of America remains the greatest source for freedom and opportunity that the world has ever known.

