#+TITLE: Control of Our Energy Future
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 

Hi everybody. Earlier this week, I spent some time with the hardworking men and women of the American auto industry, who are busy writing a new chapter in American's story. Just a few years ago, their industry was shedding hundreds of thousands of jobs. Two of the Bug Three - GM and Chrysler - were on the brink of failure. If we had let this great American industry collapse - if we had let Detroit go bankrupt - more than one million Americans would lost their jobs in the middle of the worst recession since the Great Depression. I refused to let that happen. 

These jobs are worth more than just a paycheck - they're a source of pride and a ticket to the middle class. These companies are worth more than just the cars they build - they're a symbol of American innovation and a source of our manufacturing might. So in exchange of help, we demanded responsibility. We got the companies to retool and restructure. Everyone sacrificed. And three years later, the American auto industry is back. Today, GM is the number one automaker in the world. Chrysler is growing faster in American than any other car company. Ford is investing billions in American plants and factories, and plans to bring thousands of jobs back home. All told, the entire industry has added more than 200,000 new jobs over the past two and a half years. And they're not just building cars again - they're building better cars. Thanks to new fuel efficiency standards we put in place, they are building cars that will average nearly 55 miles per gallon by the middle of the next decade. That's almost double what they get today. That means folks will be able to fill up every two weeks instead of every week, saving the typical family more than $8,000 at the pump over time. That's a big deal, especially as families are yet again feeling the pinch from rising gas prices. 

So what's happening in Detroit will make a difference. But it will not solve everything. There's no silver bullet for avoiding spikes in gas prices every year. There's no shortcut to taking control of our energy future. We have to pursue an all of-the above strategy that helps develop every source of American energy. And we have to do it now. The good news is, we've been making progress. Take a look at this chart. Six years ago, 60% of the oil we used was imported. Since I took office, America's dependence on foreign oil has decreased every single year. In fact, in 2010, for the fist time in thirteen years, less than half the petroleum we consumed was imported. Part of that is because we're producing more oil here at home than at any time in the last eight years. 

But we can not just drill our way out of this problem. While we consume 20 percent of the world's oil, we only have 2 percent of the world's reserves. 
