#+TITLE: Why we go to school?
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-11-26

Hello, everybody! Thank you. Thank you. Thank you, everybody.

All right, everybody go ahead and have a seat.

How is everybody doing today? How about Tim Spicer?

I am here with studenties at Wakefield High School in Arlington, Virginia.

And we've got students tuning in from all across American, from kindergarten through 12th grade.

And I am just so glad that all could join us today.

And I want to thank Wakefield for being such an outstanding host.

Give yourselves a big round of applause.

I know that for many of you, today is the first day of school.

And for those of your in kindergarten, or starting middle or high school, it's your first day in a new school, so it's understandable if you're a little nervous.

I imagine there are some seniors out there who are feeling pretty good right now - with just one more year to go.

And no matter what grade you're in, some of you are probably wishing it were still summer and you could've stayed in bed just a little bit longer this morning.

I know that feeling. When I was young, my family lived overseas. I lived in Indonesia for a few years. And my mother, she didn't have the money to send me where all the American kids went to school, but she thought it was important for me to keep up with an American education. So she decided to teach me extra lessons herself, Monday through Friday. But becsuse she had to work, the only time she could do it was at 4:30 in the morning. Now, as you might imagine, I wasn't too happy about getting up that early. And a lot of times, I'd fall asleep right there at the kitchen table. But whenever I'd complain, my mother would just give me one of those looks and she'd say, "This is no pinic for me either, buster."

So I know that some of you are still adjusting to being back at school. But I'm here today because I have someting important to discuss with you. I'm here because I want to talk with you about your education and what's expected of all of you in this new school year.

Now, I've given a lot of speeches about education. And I've talked about responsibility a lot. I've talked about teacher's responsibility for inspiring students and pushing you to learn. I've talked about your parents' responsibility for making sure you stay on track, and you get your homework done, and don't spend every waking hour in front of the TV or with the Xbox. I've talked a lot about your government's responsibility for setting high standards, and supporting teachers and principals, and turning around schools that aren't working, where students aren't getting the opportunities that they deserve. But at the end of the day, we can have the most dedicated teachers, the most supportive parents, the best schools in the world - and none of it will make a difference, none of it will matter unless all of you fulfill your responsibilities, unless you show up to those schools, unless you pay attention to those teachers, unless you listen to your parents and grandparents and other adults and put in the hard work it takes to succeed.

Than's what I want to focus on today: the responsibility each of you have for your education. I want to start with the responsibility you have to yourself. Every single one of you have someting that you're good at. Every single one of you have something to offer. And you have a responsibility to yourself to doscover what that is. That's the opportunity an education can provide. 

Maybe you could be a great writer - maybe even good enough to write a book or articles in a newspaper - but you might not know it until you write that English paper - that English class paper that's assigned to you.


