#+TITLE: Happy New Year Speech in 2012
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2012-01-01

Hello, everybody. As 2011 comes to end and we look ahead to 2012, I want to wish everyone a happy and healthy New Year. The last year has been a time of great challenge and great progress for our country. We ended one war and began to wind down another. We dealt a crippling blow to al-Qaeda and made America more secure. We stood by our friends and allies around the world through natural disasters and revolutions. And we began to see signs of economic recovery here at home, even as too many Americans are still struggling to get ahead. There's no doubt that 2012 will bring even more change.

And as we head into the New Year, I'm hopeful that we have what it takes to face that change and come out even stronger - to grow our economy, create more jobs, and strengthen the middle class. I'm hopeful because of what we saw right before Christmas, when Members of Congress came together to prevent a tax hike for 160 millions Americans - saving a typical family about $40 in every paycheck. They also made sure Americans looking for work won't see their unemployment insurance cut off. And I expect Congress to finish the job by extending these provisions through the end of 2012. It was good to see Members of Congress do the right thing for millions of working Americans.

But it was only possible because you added your voices to the debate. Through email and Twitter and over the phone, you let your representatives know what was at stake. Your lives. Your families. Your well-being. You had the courage to believe that your voices could make a difference. And at the end of the day, they made all the difference. More than anything else, you are the ones who make me hopeful about 2012. Because we've got some difficult debates and some tough fights to come. 

As I've said before, we are at a make-or-break moment for the middle class. And in many ways, the actions we take in the months ahead will help determine what kind of country we want to be, and what kind of world we want our children and grandchildren to grow up in. As President, I promise to be everything I can to make America a place where hard work and responsibility are rewarded - one where everyone has a fair shot and everyone does their fair share. That's the America I believe in. That's the America we've always know. And I'm confident that if we work together, and if you keep reminding folks in Washington what's at stake, then we will move this country forward and guarantee every American the opportunities they deserve. 

Thanks for watching, and from Michelle, Malia, Sasha, Bo and myself, Happy New Year.
