#+TITLE: Transportation Bill
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-12-12

Hello, everybody. This week, I traveled across the country to talk about my all-of-the-above energy strategy for America - a strategy where we produce more oil and gas here at home, but also more biofuels and fuel-efficient cars; more solar power and wind power and other sources of clean, renewable energy.

Now, you wouldn't know it by listening to some of the folks running for office out there today, but producing more oil at home has been, and will continue to be, a key part of my energy strategy.

Under my Administration, we're producing more oil than at any other time in the last eight years.

We're quadrupled the number of operating oil rigs to a record high. And we've added enough oil and gas pipeline to circle the entire Earth and then some.

Those are facts. But as I've been saying all week, even though America uses around 20% of the world's oil, we only have around 2% of the world's known oil reserves. So even if we drilled everywhere, we'd still be relying on other countries for oil.

That's why we're pursuing an all-of-the-above strategy. We're producing more biofuels. More fule-efficient cars. More solar power. More wind power.

This week, I was in Boulder City, Nevada, where they've got the largest solar plant of its kind anywhere in the country. That's the future. I was at Ohio State University, where they've developed the fastest electric car in the world. That's the future. I don't want to cede these clean energy industries to China or Germany or any other country.

I want to see solar panels and wind turbines and fuel-efficient cars manufactured right here in America, by American works.

Now, getting these clean energy industries to locate here requires us to maintain a national commitment to new research and development.

But it also requires us to build world-class transportation and communication network, so that any company can move goods and sell products all around the world as quickly and efficiently as possible.

So much of American needs to be rebuilt right now. We've got crumbling roads and bridges. A power gride that wastes too much energy. An incomplete hight-speed broadband network.

We've got thousands of unemployed contructure workers who've been looking for a job ever since the housing market collapsed. But once again, we're waiting on Congress.

You see, in a matter of days, funding will stop for all sorts of transportation projects. Construction sites will go idle. Workers will have to go home. And our economy will take a hit.

This Congress cannot let that happen. Not at a time when we should be doing everything in our power - Democrats and Republicans - to keep this recovery moving forward.

The Senate did their part. They passed a bipartisan transportation bill. It had the support of 52 Democrats and 22 Republicans.

Now it's up to the House to follow suit; to put aside partisan posturing, end the gridlock, and do what's right for the American people. This is common sense. Right now, all across this country, we've got contractors and construction workers who have never been more eager to get back on the job.

A long term transportation bill would put them to work. And those are good jobs.
通过一个长期的运输法案可以让他们回来工作，这些都是很好的工作。

We just released a report that shows nearly 90% of the construction, manufacturing and trade jobs created through investments in transportation projects are middle class jobs.
我们刚刚发布了一份报告，该报告显示，通过交通运输项目可以带动创建有关建筑、制造和贸易的工作机会，这些工作机会中的 90% 属于中层阶级。


Those are exactly the jobs we need right now, and they'll make the economy stronger for everybody.

We've done this before. During the Great Depression, American built the Hoover Dam and the Golden Gate Bridge. After World War II, we connected our states with a system of highways.

Democratic and Republican administrations invested in great projects that benefited everybody, from the workers who actually built them to the businesses that still use them today.

So tell Congress that if we invest in new technology and new energy; in new roads and bridges and construction projects, we can keep growing our economy, put our people back to work, and remind the world why the United States is the greatest nation on Earth.

Thanks and have a great weeken.

