#+TITLE: Made in America
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2012-01

As you can see, I brought a few things with me for this week's video. A padlock. A pair of boots. A candle. And a pair of socks. No, we're not having a yard sale. And these products may not appear to have much in common. But they're united by three proud words:"Made in America."

They're manufactured by American workers, in American factories, and shipped to customers here and around the world. The companies that make these products are part of a hopeful trend: they're bringing jobs back from overseas. You've heard of outsourcing - well, this is insourcing. And in this make or break moment for the middle class and those working to get into middle class, that's exactly the kind of commitment to country that we need. 

This week, I invited executives from businesses that are insourcing jobs to a forum at the White House. These are CEOs who take pride in hiring people in America, not just because it's increasingly the right thing to do for their bottom line, but also because it's the right thing to do for their workers and for our communities and our country. 

I told those CEOs what I'll tell any business leader: ask yourself what you can do to bring more jobs back to the country that made your success possible. And I'll make sure you've got a government that does everything in its power to help you succeed. That's why, in the next few weeks, I will put forward new tax proposals that reward companies that choose to do the right thing by bringing jobs home and investing in America - and eliminate tax breaks for companies that move jobs overseas. It's also why on Friday, I called on Congress to help me make government work better for you. 

Right now, we have a 21st century economy, but we've still a government organized for the 20th century. Over the years, the needs of Americans have changed, but our government has not. In fact, it's gotten even more complex. And that has to change. That's why I asked Congress to reinstate the authority that past presidents have had to streamline and reform the Executive Branch. This is the same sort of authority that every business owner has to make sure that his or her company keeps pace with the times. It's the same authority that presidents had for over 50 years - up until Ronald Reagan. And let me be clear: I will only use this authority for reforms that result in more efficiency, better service, and a learner government. Theses changes will make it easier for small business owners to get the loans and support they need to sell their products around the world.

For example, instead of forcing small business owners to navigate the six departments and agencies in the federal government that focus on business and trade, we'll have one department. One place where entrepreneurs can go from the day they come up with an idea and need a patent, to the day they start building a warehouse, to the day they're ready to ship their products overseas. And in the meantime, we're creating a new website - BusinessUSA - that will serve as a one-stop shop with information for businesses small and large that want to start selling their stuff around the world. This means that more small business owners will see their hard work pay off. More companies will be able to hire new workers. And we'll be able to build an economy that's not known as for paper profits or financial speculation, but for making and selling products like theses. Products "Made in America."

Thank you, and have a great weekend.

