#+TITLE: Strengthen American Manufacturing
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 

Hello, everybody. 

I'm speaking to you this week from the Boeing Plant Everett, Washington. Boeing has been in this community for half a century. But it's what they're doing today that has folks really excited; because at this plant they're building the plane of the future - the Dreamliner. It's an impressive sight. And, to be honest, part of why I came was to see it up close.

But I also came because this is a great example of how we can bring jobs and manufacturing back to America. You see, the last few decades haven't been easy for manufacturing in this country. New technology has made businesses more efficient and productive - and that's good - but it's also made a lot of job obsolete. The result has been painful for a lot of families and communities. Factories where people thought they'd retire have left town. Jobs that provided a decent living have been shipped overseas. And the hard truth is that a lot of those jobs aren't coming back. 

But that doesn't mean we have to settle for a lesser future. I don't accept that idea. In America, there's always something we can do to create new jobs and new manufacturing and new security for the middle class. In America, we don't give up, we get up. Right now, that's exactly what we're doing. Over the past 23 months, businesses have created 3.7 million new jobs. And manufacturers are hiring for the first time since the 1990s. It's now getting more expensive to do business in places like China. Meanwhile, America is more productive than ever. And companies like Boeing are realizing that even when we can't make thing cheaper than China, we can make things better. That's how we're going to compete globally. 

For Boeing, business right now is booming. Last year, orders for commercial aircraft rose by more than 50 percent. To meet that rising demand, they've put thousands of folks to work all over the country. We want to see more of this. We need to make it as easy as we can for our companies to create more jobs in America, not overseas. And that starts with our tax code. No company should get a tax break for outsourcing jobs. Instead, tax breaks should go to manufacturers who set up shop here at home. Bigger tax breaks should go to high tech manufacturers who create the jobs of the future. And if you relocate your company to a struggling community, you should get help financing that new plant, that new equipment, or training for new workers. It's time to stop rewarding businesses that ship jobs overseas, and start rewarding businesses that create job here in America. And Congress should send me that kind of tax reform right now.

Another thing we're doing is to make it easier for company like Boeing to sell their products all over the world, because more exports means more jobs. Two year ago, I set a goal of doubling U.S. exports over five years. And we're on track to meet the goal - ahead of schedule. We have a big opportunity right now to build not only a economy that will help us succeed today, but an economy that will help our kids and their kids succeed tomorrow. 

We know what we need to do. We need to strengthen American manufacturing. We need to invest in American made energy and new skills for American workers. And above all, we need to renew the values that have always made this country great: Hard work. Fair play. Shared responsibility. We can do this. Ask the folks in Everett. Right here, a few year ago, the first Dreamliner took off on its maiden trip. Thousands of employees came to watch. One was an executive office administrator named Sharon O'Hara. As Sharon saw that first plane take flight - a result of so much hard work - she got goose bumps. In her words, she said, We said we would do it and we did. That's the story of America. We said we would do it and we did. That's the can-do spirit that makes us who we are.

We've seen challenging times before. But we always emerge from them stronger. (我们曾经面临危机时刻，但我们总能从危机中走出并变得更加强大。) And that's what we're going to do again today. 

Thanks, and have a great weekend.
