#+TITLE: Continues reducing middle class taxes
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-12-06

Hi, everybody. Four years after the worst economic crisis of our lifetimes, our economy is growing again and creating jobs.

But we have much more to do.

Out task now is to build on that progress, because this nation only succeeds when we've got a growing, thriving middle class.

That's what drives me.

That's what I campaigned on for the past year.

That's what will guide me in our work over the next four years.

And I'm on the work with anyone of any party to move this country forward.

Bedause soon, we face a very clear deadline that requires us to make some big decisions on jobs and taxes, on investments and deficits.

Both parties voted to set this deadline.

And I believe both parties can work together to make these decisions in a balanced and responsibile way.

When it comes to taxes, for example, there are two paths available.

One says, if Congress fails to act by the end of this year, then everybody's taxes automatically go up - including the 98% of Americans who make less than $250,000 a year.

Our economy just can't afford that right now. You can't afford that right now. And nobody wants that to happen.

The other path is for Congress to pass a law right away to prevent a tax hike on the first $250,000 of anyone's income.

That's mean all Americans - including the wealthiest Americans - get a tax cut. And 98% of Americans, and 97% of all small business owners, won't see their income taxes go up a single dime.

The Senate has already pass a bill like this. Democrats in the House are ready to pass one, too.

All we need is Republicans in the House to come on board.

We shouldn't hold the middle class hostage while Congress debates tax cuts for the wealthy.

Let's begin our work by actually doing what we all agree on. Let's keep low taxes for middle class.

And let's get it done soon - so we can give families and businesses some good news going into the holidays season.

I know these chanllenges won't be easy to resolve. But we can do it if we work together.

That's why on Friday I sat down with Congressional leaders to discuss how we can reduce deficit in a way that strengthens our economy and protects our middle class.

It was a constructive meeting. And everyone agree that while we may have our difference, we need to come together, find soluctions and take action as soon as possible.

Because if anything, that's the message I heard loud and cleare in this election.

Work as hard as you can to make our lives better. And do it together. Don't worry about the politics. Just get it done.

Everywhere I went during the campaign - from farms Iowa to the Vegas strip, from Colorado's Rockies to the Florida coast - I was inspired by the grit resiliency American people, by your hard work and sense of decency.

And it makes me want to work even harder for you.

I saw it again this week in New York, where our fellow citizens are goting through a really tough time, but are helping each other through it. And we're gonna be there to help them rebuild.

Every single day, the good people of this country work as hard as you can to meet your responsibilities.

Those of us you sent to Washington have to do the same.

Thanks and have a greet weekend.
