#+TITLE: Meeting of the minor crime
#+AUTHOR: Bush
#+EMAIL: junahan@outlook.com
#+DATE: 2008-12-02

I am thankful that you all have come to talk to me about a very important initiative, and it's a mentoring program aimed at helping children of people who are incarcerated. I set a goal for the country that from 2003 until 2008 that we'd have 100,000 such matches with adults combined with a child who could use some love. And I'm pleased that as of September we've exceeded that goal.

And I want to thank you all for being a part of a program that hopefully is bring hope to people's lives. I think it is. First of all, I want to thank Stacey, Julia, and Destiney for sharing stories, and I wish you all the best. I hope you - you're - I know you're appreciative that Joe, Melissa, and Emilee have taken time out of their lives to help you.

I am hopeful that somebody who watches this show, watches this program, realizes that they can make a difference in a child's life; that it doesn't take much. Oh, it takes some time, it takes a little bit of extra love, but by helping a child, you can really help the country. You help yourself by loving, but you help America - one heart, one soul at a time. So, Chuck, thank you for your hospitality. 

The Youth Focus program here in Greensboro, North Carolina, is a part of Big Brothers and Big Sisters. These youngsters got ambitions and goals. They want to go to college. They want to make a difference. And I suspect that the mentors will be anxiously following the career of someone who they have - they've been able to help.

And so thank you all for coming. God bless you, and good luck to you.
