#+TITLE: Meet Dr. Halima Bashir
#+AUTHOR: Bush
#+EMAIL: junahan@outlook.com
#+DATE: 2008-12-05

I have just had the distinct pleasure and honor of visiting with Dr. Halima Bashir, who wrote a book called Tears of the Desert. This good soul brings firsthand accounts to what life is like in Darfur. She has witnessed violence, deprivation, and she carries a message of a lot of people who want our help.

I assured her that, in spite of the economic difficulties, our aid will continue to flow. We will use our influence to make sure the aid gets to the people of Darfur. I also made it clear that I am frustrated with the pace of activities; that the United Nations must expedite sending troops, peacekeepers, to provide security for the people - that's what they want, they want to be able to have a secure life - and that we'll help. The Unites States continues to stand at the ready to provide airlift. The pace of action out of the United Nations is too slow. We support the mediation process by the A.U.-U.N. mediator. In other words, we recognize in order for there to be peace in Darfur that parties must come to the table in good faith and solve the problems. 

And finally, it's very important for President Bashir of Sudan to know that he cannot escape accountability; that if he so choose, he could change people's lives, the condition of people's live very quickly. I've appointed a special envoy to Sudan to help put pressure on the government. The United States must continue to rally the international community to put pressure on the government, as well.

The urgency of the situation is never more apparent than when I had the honor of visiting with this brave soul. And so I welcome you to the Oval Office. And I welcome any comments you want to make. 

DR. BASHIR: Yes, of course.


