#+TITLE: Meet Liberia President
#+AUTHOR: Bush
#+EMAIL: junahan@outlook.com
#+DATE: 2019-01-09

Madam President, I have come to respect you and admire you because of your courage, your vision, your commitment to universal values and principles. Laura and I had a fantastic experience traveling to Liberia, and we want to thank you for your warm hospitality. Yesterday, you made note of my - the lack of my talent when it came to dancing. But nevertheless, I want you to know I danced with joy. 

And no question Liberia has gone through very difficult times. But no question there's a bright future for Liberia. Liberia need the help of the United States and other nations to help make sure children are educated, to make sure babies are not dying because of malaria, to make sure there's an infrastructure so that small businesses can flourish, to make sure the port is open for business. We have been helpful and we want to be helpful in the future.

And I'm confident in saying to the American people that by helping this President and Liberia, we really help ourselves in many ways. And so I - it's been a joy to know you. It's been a great experience working with you, and I congratulate you on your strong leadership. Welcome.

Thank you, Mr, President.

I come on behalf of the Liberia people to thank you for the support we've received from you, the administration, from Congress, from the American people. It has enabled us to turn the corner form being what was called a failed state several years ago to today what we hope will becoming to be one of the emerging democracies. We've been able to put our economic and financial house in order; tackle our debt; begin to rebuild our infrastructure; put our children back into school; bring some water and electricity to a country that hasn't had it for over two decades. And so we're just so thankful for the encouragement, the support that we received from you. 

I want you to know that the challenges are many, but with the continued support of the American people and the continued support of the American administration and Congress, that we feel that Liberia can become a post-conflict success story. We want to say to you that your visit to our country is one that goes down in the record books as being one of the most enjoyable - not only for the dancing - but for all that you did to train our new soldiers and put our infrastructure in order; and the hope that you helped to give to the Liberia people that indeed the nightmare is over and they can have a future that's full of promise. So we're here to say to you we're very greatful. The Liberia people just want to thank you.

Thank you. 

And thank Laura, especially, who was there with you. And we're just so pleased - just tell.

Thank you, Madam President. Thank you.

