#+TITLE: Speech to economy recession
#+AUTHOR: Bush
#+EMAIL: junahan@outlook.com
#+DATE: 2008-12-05

Welcome to the White House. Yes! We're excited you are here. And we're excited you're here for a couple of reasons:

One, we love to see the wonder in people's eyes when they get to see the majesty of the White House at this time of year. And I'm looking in your eyes and I'm seeing wonder.

Secondary, I am glad you're here because I wanted to thank your moms and dads for serving the United States of America. We love being with our military families because it gives us a chance to express the sincere and deep appreciation of all Americans for the sacrifices that families make. So I want to thank you for standing by your moms and dads, and telling them you're proud of them, and telling them you love them.

Thirdly, I'm going to ask you to do us a favor, and that is when you email mom and dad, just tell them you came by the White House, and the President and Laura, the First Lady, send a special holiday greeting. So you'll be the messenger. So your job is to say we respect your mom and dad, we admire your mom and dad, and we pray for your mom and dad. So would you do that for us? 

Yes.

And fourthly, I'm glad to be here because I get to introduce my wife. It's a pretty neat thing, isn't it? 

Yes.

Now, Laura tells me you've already seen Santa, had a few cookies -- 

Yes.

Yes? I'm surprised there's not more wiggling going on. At any rate, please welcome my dear wife, First Lady Laura Bush.

Thank you very much, Mr. President. And thank you to each and every one of you who've come today. Every year, at this time of year, at the holiday season, we have a really fun event with boys and girls from different parts of country. And today, I'm happy to welcome students here from Russell Elementary at Quantico Marine Base in Virginia. Where are all the Russell Elementary kids? Great. Thank you all for coming. And we have some kids from Dahlgren School at Dahlgren Navy Base in Virginia. Thank you all for coming. And we have West Meade Elementary from Fort Meade Army Base in Maryland. Thanks so much for you all coming. How many of you have a parents who's deployed? You have some parents who are in Iraq or Afghanistan, or somewhere else? Or on a ship. Most of you don't? Okay. Well, thank you parents for all of us.

We have a very special treat for our entertainment today. Fist, though, I want you to look at these Christmas trees, and you can tell by looking at them what our holiday theme is, and that's it's A Red, White, and Blue Christmas. Can you tell it?

Yes.

And what does that mean? What is red, white, and blue?

Our flag.

Our flag. That's right. Those are our country's colors - red, white, and blue. So this is a chance, on our very last Christmas here at the White House, to celebrate our country. And we're doing it by painting everything red, white, and blue. You probably saw the bunting on the garlands in the hall. And then if you looked at the big, big, blue Christmas tree in the Blue Room, you saw all those ornaments that represent every part of the United States. Did you see any those?

Yes.

Good. Okay, today we have a special treat. We've invited a brass band to the White House to perform some fun versions of your favorite holiday songs. These musicians are right here - from right here in Washington. They play at the United House of Prayer, which is a church in Anacostia. And we hope you will enjoy their unique style of music, which is performed in a gospel brass band tradition particular to their denomination. See if you can hear how the band's 16 instruments come together to sound like a gospel choir, with trombones playing different voices in harmony.

So now, I'm delighted to introduce the Sweet Heaven Kings.


