#+TITLE: Speech to world AIDS day
#+AUTHOR: Bush
#+EMAIL: junahan@outlook.com
#+DATE: 2008-12-01

Good morning. Today is World AIDS Day, a day we reaffirm to our commitment to fight HIV/AIDS at home and abroad. 

Thirty-three million people around the world are living with HIV, including more than one million Americans. Once again this year, to observe World AIDS Day, there is a red ribbon on the North Portico of the White House. The ribbon is a symbol of our resolve to confront HIV/AIDS and to affirm the matchless vale of every life. 

One of the most important initiatives of my administration has been the Emergency Plan for AIDS Relief, know as PEPFAR. It's a largest international health initiative dedicated to a single disease. When we launched PEPFAR, our goal was to support treatment for two million people in five years. Today, I'm pleased to announce that we have exceeded that goal - early. The American people, through PEPFAR, are supporting lifesaving treatment for more than two million people around the world. And when PEPFAR began, only 50,000 people living with HIV in all of sub-Sahara Africa were receiving antiretroviral treatment. Around the world, we've also supported care for more than 10 million people affected by HIV, including more than four million orphans and vulnerable children. More than 237,000 babies have been born HIV-free, thanks to the support of the American people for programs to prevent mothers from passing the virus on to their children.

PEPFAR is bringing hope and healing to people around the world. On our trips to Africa, Laura and I have witnessed firsthand the gratitude of the Africa people. We look forward to discussing our efforts to combat global HIV/AIDS with Rick Warren at the Saddleback Civil Forum on Global Health this morning. In the meantime, we thank our fellow citizens for being so compassionate and so caring and so decent God bless.
 
