#+TITLE: Hyppy Thanksgiving
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-12-14

On behalf of the Obama family - Michelle, Malia, Sasha, Bo and me - I want to wish everybody a very hyppy Thanksgiving.

For us, like so many of you, this is the day full of family and friends; food and football.

It's a day to fight the overwhelming urge to take a nap - at least until after dinner.

But most of all, it's a time to give thanks for each other, and for the incredible bounty we enjoy this country.

That's especially important this year. As a nation, we've just emerged from a campaign season that was passionate, noisy, and vital to our democracy.

But it also required us to make choices - and sometimes those choices led us to focus on what sets us apart instead of what ties us together; on what candidate we support instead of what country we all belong to.

Thanksgiving is a chance to put it all in perspective - to remember that, despite our differences, we are, and always will be, Americans first and foremost.

Today we give thanks for blessings that are all too rare in this world.

The ability to spend time with the ones we love; to say what we want; to worship as we please; to know that there are brave men and women defending our freedom around the globe; and to look our children in the eye and tell them that, here in America, no dream is too big if they're willing to work for it.

We're also greatful that this country has always been home to Americans who see these blessings not simply as gifts to enjoy, but as opportunities to give back. Americans who believe we have a responsibility to look out for those less fortunate - to pull each other up and move forward together.

Right now, as we prepare to gather around our dinner tables, there are families in the northeast who don't have luxury. Many of them have lost everything to Hurricane Sandy - homes, possessions even loved ones. And it'll be a long time before life gets back to normal.

But in the midst of so much tragedy, there are also glimmers of hope.

Over the last few weeks, we've seen FEMA personnel, National Guard and first responders working around the clock in hard-hit communities.

We've seen hospital workders using their lunch breaks to distribute supplies. Families offering up extra bedrooms. The fire department advertisting free hot showers. Buses full of volunteers coming from handreds of mile away. Neighbors sharing whatever they have - food, water, electricity - and saying again and again how lucky they are to have a roof over their heads.

It would've been easy for these folks to do nothing - to worry about themselves and leave the rest to someone else.

But that's not who we are. That's not what we do.

As Americans, we are bold, generous, big-hearted people.

When our brothers and sisters are in need, we roll up our sleeves and get to work - not for the recognition or the reward, but because it's the right thing to do. Because there but for the grace of God go I.

And because here in America, we rise or fall together, as one nation and one people.

That's something to be greatful for - today and everyday.

So to all the Americans doing your part to make our world a better place - it is my great privilege to serve as your President.

To all our service members - it is my honor to be your Commander in Chief.

And from our family to yours, happy Thanksgiving everybody.
