#+TITLE: Nominate Supreme Court
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2019-01-03 (2016-04-21)

Hello, everybody. One of America's greatest strengths is our free market. A thriving private sector is the lifeblood of our economy - it's how we create jobs, expand opportunities, and give everybody a shot at success. It's what has made America the strongest country on Earth.

The most essential ingredient in a healthy free market is competition. But right now, too many companies are engaging in behaviors that stifle competition - like blocking new competitors from entering the market or limiting the information and options that give consumers real choice. As a consequences, the rest of use pay higher prices for lower quality products and services. Workder receive lower wages than they otherwise would. Small businesses and entrepreneurs can get squeezed out of the market. And none of that is fair - or good for our economy.

The deck should not be stacked in favor of the wealthiest individuals and the biggest corporations, against working Americans. That's why my administration is doing everything we can to reverse this trend and promote more competition in the marketplace. 

In addition to enforcing the rules on the books, I've directed federal agencies to identify anti-competition behavior in different industries, and find new and sepecific ways to promote competition.

One industry that's ripe for change is cable TV. Right now, 99 percent of cable and satellite TV customers rent set-top boxes from their providers. According to one survey, this costs households an average of more than $230 per year. We spend some $20 billion to rent these devices. While we have almost unlimited choice in what we watch on television, from traditional programming to online content, there's next to no competition to build a better, user-friendly product that allows you to easily access all this content in one place.

Some most consumers just rent whatever the cable company offers. Because we have to. That means companies have little incentive to innovate. As a consequences, we need multiple devices and controllers to access content from different sources. That make no sense. So my administration has encouraged the FCC to remove the barries to competition that prevent new players from offering innovative cable box options to consumers. 

We know this weeks. For years, Americans had to rent our telephones from the phone company. This was a while ago, but when the FCC finally unlocked competition for home phones, the marketplace was flooded with all kinds of phone options with new features, and at different price points. Consumers suddenly had many options. And the whole industry moved forward as a result.

The same can happen with cable boxes, and in dozens of areas of our economy - all of which can make a different in your everyday life. The bottom line is, competition is good for consumers, workers, businesses, and our economy.

So I'm going to keep doing everything I can to make sure that our free market works for everyone.

Thanks, and have a great weekend.





