#+TITLE: Disease of Addiction
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-12-26 (2016-05-17)

Hi, everybody. I've got a special guest with me this week - Macklemore.

For those of you who don't share the same love for hip-hop that I do, he's a Grammy-winning artist - but he's also an advocate who's giving voice to a disease we too often just wisper about: the disease of addiction.

Hey, eveybody. I'm here with President Obama because I take this personally. I abused prescription drugs and battled addiction. If I hadn't gotten the help I needed when I needed it, I might not be here today. And I want to help others facing the same chanllenges that I did.

Drug overdoses now take more lives every year than traffic accidents. Deaths from opioid overdoses have tripled since 2000. A lot of the time, they're from legal drugs prescribed by a doctor. So addiction doesn't always start in some dark alley - it often starts in a medicine cabinet. In fact, a new study released this month found that 44 percent of Americans know someone who has been addicted to prescription painkillers.

I didn't just know someone - I lost someone. My friend Kevin overdosed on painkillers when he was just 21 years old. Addiction is like other disease - it doesn't discriminate. It doesn't care what color you are, whehter you're a guy or girl, rich or poor, whether you live in the inner-city, a suburb, or rural America. This doesn't just happen to other people's kids or some other neighborhood. It can happen to any of us. 

That's why just talking about this crisis isn't enough - we need to get treatment to more people who need it. My administration is working with communities to reduce overdose deaths, including with medication. We're working with law enforcement to help people get into treatment instead of jail. And under Obamacare, health plans in the Marketplace have to include coeverage for treatment. 

I know recovery isn't easy or quick, but along with the 12-step program, treatment has saved my life. Recovery works - and we need our leaders in Washington fund it and people know how to find it. 

We all need to do more to make that happen. I've asked Congress to expand access to recovery services, and to give first responders the tools they need to treat overdoses before it's too late. This week, the House passed several bills about opioids - but unless they also make actual investments in more treatment, it won't get Americans the help they need. On top of funding, doctors also need more tranining about the power of the pain medication they prescribe, and the risks those pain medication carry. Another way our country can help those suffering in private is to make this conversation public. 

When you're going through it, it's hard to imagine there could be anything worse than addiction. But shame and stigma associated with the disease keeps too many people from seeking the help they actually need. Addiction isn't a personal choice or a personal failing. And sometimes it takes more than a strong will to get better - it takes a strong community and accessible resources. 

The good news is, there's hope. When we talk about opioid abuse as the public health problem it is, more people will seek the help they need. More people will find the strength to recover, just like Macklemore and millions of Americans have. We'll see fewer preventalbe deaths and fewer broken families. 

We have to tell people who need help that it's OK to ask for it. We've got to make sure they know where to get it. 

We all have a role to play. Even if we haven't fought this battle in our own lives, there's a good chance we know someone who has, or who is.

President Obama and I just had a powerful conversation here at White House about opioid abuse, and what we can do about it. You can catch it this summer on MTV. And to find treatment in your area, call 1-800-662-HELP.

Thanks everybody, thanks Macklemore, and have a great weekend.





