#+TITLE: Aurora Shooting
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-12-9

As many of you know, early on Friday, at least 12 people were killed when a gunman opened fire at a movie theater in Aurora Colorado.

Dozens more are being treated for injuries at local hospitals. Some of the victims are being treated at a children's hospital.

We are still gathering all the facts about what happened, but we do know that the police have one suspect in custody.

And the federal government stands ready to do everything necessary to bring whoever's responsible for this heinous crime to justice.

We will take every step possible to ensure the safety of all our people.

And we will stand by our neighbors in Colorado during this extraoridinarily difficult time.

Even as we come to learn how this happend and who's responsible, we may naver understand what leads anyone to terrorize their fellow human beings.

Such evil is senseless - beyond reason. But while we will never know fully what causes someone to take the life of another, we do know what makes life worth living.

The people we lost in Aurora loved, and were loved. They were mother and farters; husbands and wives; sisters and brothers; sons and daughters; friends and neighbors.

They had hopes for the future and dreams that were not yet fulfilled.

And if there's anything to take away from this tragedy, it's a reminder that life is fragile.

Our time here is limited and it is precious.

And what matters in the end are not the small and trivial things which so often consume our lives. It's how we choose to treat one another, and love one another. It's what we do on a daily basis to give our lives meaning and give our lieves purpose.

That's what matters. That's why we're here.

I'm sure many of you who are parents had the same reaction I did when you first heard this news: what if it had been my daughters at the theater, doing what young children enjoy doing every day?

Michelle and I will be fortunate enough to hug our girls a little tighter this weekend, and I'm sure you will do with your children. But for those who may not be so fortunate, we need to embrace them and let them know we will be there for them as a nation.

This weekend I hope everyone takes some time for prayer and reflection - for the victims of this terrible tragedy, for the people who knew them and lolved them, for those who are still struggling to recover, and for all the victims of the less publicized acts of voilence that plague our communities on a daily basis.

Let's keep all theses Americans in our prayers.

And to the people of Aurora, may the Lord bring you comfort and healing in the hard days to come.




