#+TITLE: White House Correspondents' Dinner (2015)
#+AUTHOR: Obama
#+EMAIL: junahan@outlook.com
#+DATE: 2018-11-27

Good evening, everybody. Welcome to the White House Correspondents' dinner.

A night when Washington celebrates itself. Somebody's got to do it. And welcome to the fourth quarter of my presidency. It's true...that's Michelle cheering.

The fact is I feel more loose and relaxed than ever. Those Joe Biden shoulder massages they're like magic. You should try one. Oh, you have.

I am determined to make the most of every moment I have left. After the midterm elections, my advisors asked me "Mr. President, do you have bucket list?" And I said, "Well, I have something that rhymes with bucket (fuck it) list."

...... Take executive action on immigration. Bucket. (fuck it)

New climate regulations. Bucket. It's the right thing to do. My new attitude is paying off. Look at my Cuba policy.

The Castro brothers are here tonight. Welcome to American, amigos. Que pasa? What? It's the Castros from Texas. Oh, Hi, Joaquin. Hi, Julian.

Anyway, being president is never easy. I still have to fix broken immigration system, issue veto threats, negotiate with Iran.

All while finding time to pray five times a day. Which is strenuous. And it is no wonder that people keep pointing out how the presidency has aged me.

I look so old, John Boehner's already invited Benjamin Netanyahu to speak at my funeral. Meanwhile, Michelle hasn't aged a day.

I ask her what her secret is and she just says "fresh fruits and vegetables." It's aggravating. Fact is though, at this point my legacy is finally beginning to take shape.

The economy is getting better. Nine in ten Americans now have health coverage. Today thants to Obamacare you no longer have to worry about losing your insurance if you lose your job. You're welcome, Senate democrats.

Look, it is true I have not managed to make everybody happy. Six years into my presidency some people still say I'm arrogant, aloof, condescending. Some people are so dumb.

No wonder I don't meet with them. And that's not all people say about me. A few weeks ago, Dick Cheney says he thinks I'm the worst president of his lifetime.

Which is interesting because I think Dick Cheney is the worst president of my lifetime. Quite a coincidence. I mean everybody's got something to say these days.

Mike Huckabee recently said people shouldn't join our military until a true conservative is elected president. Think about that. It was so outrageous 47 Ayatollahs wrote us a letter trying to explain to Huckabee how our system works.

It gets worse. Just this week, Michele Bachmann actually predicted that I would bring about the biblical end of days. Now, that's a legacy. That's big. I mean, Lincoln, Washington, they didn't do that.

...... You know, I just have to put this stuff aside. I have to stay focused on my job.

Because for many Americans this is still a time of deep uncertainty. For example, I have one friend, just a few weeks ago, she was making millions of dollars a year and she's now living out of a van in Iowa.

...... Meanwhile, back here in our nation's capital we're always dealing with new challenges.

I'm happy to report that the Secret Service - thanks to some excellent reporting by white house correspondents - they are focusing on some of the issues that have come up. And they have finally figured out a fool proof way to keep people off my lawn. [image of John McCain]It works.

It's not just fence jumpers. Some of you know, a few months ago, a drone crashed landed out back. That was pretty serious, but don't worry, we installed a new state-of-the-art security system. [image of Joe Biden]......

You know, let me set the record straight. I tease Joe Biden, but you know he has been in my side for seven years. I love that man. He's not just a great Vice President, he is a great friend. We've gotten so close in some places in Indiana, they won't serve us pizza anyore. 

I want to thank our host for the evening, a Chicago girl, the incredibly talented Cecily Strong. On Saturday Night Live, Cecily impersonates CNN anchor Brooke Baldwin, which is surprising, because usually the only people impersonating journalists on CNN are journalists on CNN. ABC is here with some of the stars from their big new comedy "Black-ish". It's great show, but I have to give ABC fair warning, being black-ish only makes you popular for so long. Trust me. There is a shelf life to that thing. 

As always, the reporters here had a lot to cover over the last year here on the East Coast.

One big story was the brutal winner. The polar vortex caused so many record lows, they renamed it MSNBC. But, of course, let's face it, there is one issue on every reporters minds, and that is 2016. Already, we've seen some missteps.

It turns out Jed Bush identified himeself as Hispanic back in 2009, which, you know what, I - look, I understand. It's an innocent mistake. It reminds me of when I identified myself as American back in 1961.

Ted Cruz said that denying the existence of climate change made him like Galileo. Now that's not really an apt comparison. Galileo believed the Earth revolves around the sun. Ted Cruz believes the Earth revolves around Ted Cruz. And just as an aside, I want to point out, when a guy who has his face on a Hope poster calls you self-centered, you know you've got a problem.

The narcissism index is creeping up a little too high. Meanwhile, Rick Santorum announced that he would not attend the same-sex wedding of a friend or loved one, to which gays and isebians across the country responsed, that's not going to be a problem.

Don't sweat that one. And Donald Trump is here. Still. 

Anyway, it's amazing how time flies. Soon, the first presidential contest will take place, and I for one cannot wait to see who the Koch brothers pick. It's exciting.

Marco Rubio, Rand Paul, Tde Cruz, Jed Bush, Scott Walker, who will finally get that red rose? The winner gets a billion dollar war chest. The runner-up gets to be the bachelor on the next season of "The Bachelor".

I mean seriously, a billion dollars from just two guys. Is it just me, or does that feel a little excessive? I mean, it's almost insulting to the candidates.

The Koch brothers think they think to spend a billion dollars to get folks to like one of these people. It's got to hurt their feelings a little bit. And, look, I know I've raised a lot of money too, but in all fairness, my middle name is Hussein. What's their excuse?

The trail hasn't been easy for my fellow Democrats either. As we all know Hillary's private e-mail got her in trouble.

Frankly, I thought it was going to be her private Instagram account that was going to cause her bigger problems. [Shows photos of Hillary Clinton] Hillary kicked things off by goting completely unrecognized at a Chipotle.

Not to be outdone, Martin O' Malley went completely unrecognized as a Matin O' Malley campaign event. And Bernie Sanders might run. I like Bernie. Bernie's an interesting guy.

Apparently, some folks really want to see a pot-smoking socialist in the White House. We could get a third Obama term after all.

It could happen. Anyway, as always, I want to close on a more serious note. You know, I often joke about tensions between me and the press, but honestly, what they say doesn't bother me.

I understand we've got an adversarial system. I'm a mellow sort of guy. And that's why I invited Luther, my anger translator, to join me here tonight. [Keegan-Michael Key joins on stage.]

LUTHER: Hold on to your lily white butts!

OBAMA: In our fast-changing world, traditions like the White House Correspondents' dinner are important.
LUTHER: I mean, really! What is this dinner? Andy why am I required to come to it? Jeb Bush, do you really want to do this!

OBAMA: Because despite our differences, we count on the press to shed light on the most important issues of the day.
LUTHER: And we can count on Fox News to terrify old white people with some nonsense!... That was ridiculous.

OBAMA: We won't always see eye to eye.
LUTHER: And, CNN, thank you so much for the wall-to-wall Ebola coverage. For two whole weeks, we were one step away from "The Walking Dead." Then y' all got up and just moved on to the next day. That was awesome. Oh, and by the way, if you haven't noticed, you don't have Ebola!

OBAMA: But I still deeply appreciate the work that you do.
LUTHER: Y' all remember when I had that big old hole in the bottom of the gulf of Mexico, and then I plugged it? Remember that? Which Obama's Katrina was that one? Was that 19 or 20, because I can't remember.

OBAMA: Protecting our democracy is more important than ever. For example, the Supreme Court ruled that the donor who gave Ted Cruz $6 million was just exercising free speech. 
LUTHER: Yes, it's the kind of speech like this, I just wasted $6 million.

OBAMA: And it's not just Republicans. Hillary will have to raise huge sums of money too.
LUTHER: Aw yeah, she's going to get that money! She's going to get all the money! Khaleesi is coming to Westeros! Watch out! Woo!

OBAMA: The non-step focus on billionaire donors creates real problems for our democracy.
LUTHER: And that's why we're running for our third term!

OBAMA: No, we're not.
LUTHER: We're not?
OBAMA: No.
LUTHER: Who the hell said that!

OBAMA: But we need to focus on big challenges like climate changes.
LUTHER: Hey, folks, if you haven't noticed, California is bone dry. It looks like a trailer for the new "Mad Max" movie up in there. Y' all think that Bradley Cooper came here because he wants to talk to Chuck Todd? He needed a glass of water! Come on.

OBAMA: The science is clear, the science is clear. Nine out of the 10 hottest years ever came in the last decade.
LUTHER: Now I'm not a scientist, but I do know how to count to ten.

OBAMA: Rising seas, more violent storms ...
LUTHER: You got mosquitoes, sweaty people on the trains stinking it up. It's just nasty!

OBAMA: I mean, look at what's happening right now. Every serious scientist says we need to act. The pentagon says it's a national security risk. Miami floods on a sunny day and instead of doing anything about it, we've got elected officials throwing snowballs in the Senate.
LUTHER: Okay, I think they got it, bro.

OBAMA: It is crazy! What about our kids? What kind of stupid, short-sighted irresponsible bull - 
LUTHER: Whoa, whoa whoa, whoa!
OBAMA: What?
LUTHER: Hey!
OBAMA: What?
LUTHER: All due respect, sir, you don't need anger translator. You need counseling.
LUTHER: And I'm out of here, man. I ain't trying to get into all this.
OBAMA: Go.

LUTHER:[to Michael Obama] He is crazy.

OBAMA: Luther, my anger translator, ladies and gentlemen. Now that I got that off my chest - you know, investigative journalism, explanatory journalism, journalism that exposes corruption and the marginalized, the voiceless - that's power. It's privilege.

It's as important to American's trajectory, to our values, our ideas, than anything that we could do in elected office. We remember journalists we lost over the past year.

Journalists like Steven Sotloff and James Foley, murdered for nothing more than trying to shine a light into some of the world's darkest corners ......

We remember the journalists unjustly imprisoned around the world, including our own Jason Rezaian. For nine months, Jason has been imprisoned in Tehran for nothing more than writing about the hopes and the fears of the Iranian people, carrying their stories to the readers of "The Washington Post," in an effort to bridge our common humanity.

As we already mentioned, Jason's brother Ali is here tonight and I have told him personally, we will not rest until we bring him home to his family safe and sound. Theses journalists and so many others view their work as ore than just a profession, but as a public good, an indispensable pillar of our society, so I want to give a toast to them.

...... I raise a glass to them and all of you, with the worlds of the American foreign correspondent Dorothy Thompson. It is not the fact of liberty but the way in which liberty is exercised that ultimately determines whether liberty itself survives. Thank you for your devotion to exercising our liberty and to telling our American story. God bless you. God bless the United States of American.

